### PR TITLE
Improve unusedArgumentException message

### PR DESCRIPTION
**Pull request by Ello250**
I have reworked the way the unused exception I added works so that the arguments that go unused can be added to the message to give a better idea of what went wrong. Also I have added a write line option for the console.

### CODE REVIEW

**Comment by RSuter** [comment]
Looks good, thanks for the PR. However, please do not change the interface of IConsoleHost as it is a breaking change for a lot of users. Can you revert the changes of ConsoleHost.cs and IConsoleHost.cs? Then it is fine for me...

**Comment by Ello250** [comment]
Sure, will do it now

**Comment by RSuter** [comment]
Thanks... v3.11 released.

**Comment by RSuter** [comment]
https://ci.appveyor.com/project/rsuter/nconsole/deployment/1203625
I hope it is available soon.

**Pull request merged**
